spring:
  application:
    name: ${service.name}
    desc: WebHook Service
  cloud:
    stream:
      function:
        definition: artifactEvent
      bindings:
        artifactEvent-in-0:
          group: webhook
          destination: artifactEvent
          binder: pulsar
server:
  port: __BK_REPO_WEBHOOK_PORT__
logging:
  path: ${logging.path-common}/${service.name}
service:
  name: webhook
webhook:
  domain: ${cluster.self.url}/webhook
  maxRequests: 1000
  maxRequestsPerHost: 1000
  filterProjectRepoKey:
    - '*:report'
    - '*:log'
